CREATE TABLE IF NOT EXISTS Logs (
  id BIGSERIAL PRIMARY KEY,
  provider VARCHAR(32) NOT NULL,
  recipient TEXT NOT NULL,
  message TEXT NOT NULL,
  ip inet NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
